version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoice_generator

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - invoice_generator
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:

networks:
  invoice_generator:
